### ISSUE TITLE
Configurable "auth" middleware

### ISSUE THREAD

**Issue by bastos71** [jeremykenedy/laravel2step#12]
Hello there,

I installed this package in a small [backpack](https://backpackforlaravel.com/) project and I had an issue with the middleware.
The first error I encountered was **Route [login] not defined.** when trying to login, after being automatically redirected to `/verification/needed`

According to [this line of code,](https://github.com/jeremykenedy/laravel2step/blob/285c1750f104f45dcba4c850beae74c47cde7684/src/app/Http/Controllers/TwoStepController.php#L29), the middleware used by the package is "auth", it should be told in the installation steps to create a middleware group `auth` in case of need. **Or may be let the possibility to configure it ?** 
For example in my project I had to add this in `App\Http\Kernel` : 

```php
    protected $middlewareGroups = [
        // ...
        'admin' => [
            'twostep',
        ],

        'auth' => ['admin'],
        //...
    ];
```

**Comment by jeremykenedy** [comment]
auth is the default Laravel authentication middleware. Since backpack is a custom framework based on Laravel and is not an MIT licensed product I would suggest forking them and customizing it to what you need. Releasing a version of the fork then calling that version overriding it in your composer.json file/

Here is an example of how to call your fork:
* https://github.com/jeremykenedy/laravel-auth/blob/master/composer.json#L37
* https://github.com/jeremykenedy/laravel-auth/blob/master/composer.json#L51
