### ISSUE TITLE
iOS input not solved

### ISSUE THREAD

**Issue by Mokei-it** [jeremykenedy/laravel2step#7]
Hi Jeremy,
thank you very much for your kind attention to the issue I wrote two month ago.
I'm sorry to tell you that the solution you made doesn't solve the problem.
However, after many attempts I discovered a behavior that I hope will help you finding a solution:

- so far, the only way to type in the first character is to copy it from the email and paste it in the first field.

- To input the second character you must leave the cursor  in the first field and type in the second character that automatically will be placed in the second field and so on.

Please, let me know if there's anything I can help you with this issue.

**Comment by jeremykenedy** [comment]
This is fixed in the most recent version of this package.

I found that in older versions the error is in the view here https://github.com/jeremykenedy/laravel2step/blob/master/src/resources/views/scripts/input-parsing-auto-stepper.blade.php#L5

In an older version if you published the views it was using `keydown`. `keyup` is what is using now and that works on IOS.
